version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: infodengue_am_2022
      - name: populacao_2022
      - name: faixa_etaria1_2022
      - name: faixa_etaria2_2022
      - name: faixa_etaria3_2022
      - name: genero_2022